services:
  - type: web
    name: tours-and-tour
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
        placeholder: "e.g., xyz7@gmail.com"
      - key: ADMIN_PASSWORD
        sync: false
        placeholder: "e.g., 1234"
      - key: MONGODB_URI
        sync: false
        placeholder: "Your MongoDB Atlas Connection String"
